### ISSUE TITLE
Waves 2.0 TODO List

### ISSUE THREAD

**Issue by bonomat** [comit-network/waves#138]
TODO list

- [x] get status
- [x] get balance
- [ ] fix waves_script to start extension and frontend 
  - partially done: not fully automated and frontend and extension need to be started separately
- [x] show balance in extension
- [x] show address in extension
- [x] fund wallet with faucet
- [x] get buy swap_payload
- [x] get sell swap_payload
- [x] sign and send transaction
- [x] display decoded transaction before signing and ask for user confirmation
- [x] wallet_lib does not need to be aware of wasm, e.g. create new module for wallet in background script and use wallet_lib directly
- [x] Update UI e2e tests (using selenium now). The wip version has two tests that create a wallet from scratch, but we should instead (1) test that we can create the wallet and (2) use that created wallet to sell bitcoin in one test, and buy bitcoin in another. For this we need to be able to run jest tests sequentially.
